### ISSUE TITLE
API: resolve discrepancy between simple map and choropleth in tooltip and popout

### ISSUE THREAD

**Issue by martinfleis** [martinfleis/geopandas-view#10]
The default behaviour of tooltip and popout is different for choropleth and simple map at the moment. This should be ideally the same or at least not confusing. I am not sure what the ideal default behaviour of these two should be, I am open to ideas.

**Comment by Sangarshanan** [comment]
could get around this by mimicking the behaviour of `folium.Choropleth` using `folium.GeoJson` and style functions, something like this https://github.com/Sangarshanan/geopatra/blob/db148e30bed5a2a99b2938f7090f0698b9b0984f/geopatra/folium/choropleth.py#L63  or rather could also attempt to monkeypatch `folium.Choropleth` to use GeoJsonTooltip and GeoJsonPopup assuming they give us the ideal behaviour. Also, another thing to note is that we would face the same issue when attempting to support circleplots and markerclusters

**Comment by martinfleis** [comment]
I already implement them for Choropleth and they work well. I just used different defaults which bothers me a bit, so you get different behaviour. So it is entirely our choice how the default will behave, that is what I wanted to resolve.

https://github.com/martinfleis/geopandas-view/blob/91432d853c73b1b9025643af92d1c3803885739a/geopandas_view/view.py#L436-L438

>  Also, another thing to note is that we would face the same issue when attempting to support circleplots and markerclusters

Hmm, will have to look into those to understand them better.

**Comment by Sangarshanan** [comment]
Did you also mean this ? popup and tooltips in Choropleth don't respect the given arguments 
![image](https://user-images.githubusercontent.com/21971847/107148424-edb53580-6978-11eb-8dad-b9453f3e46c5.png)

**Comment by martinfleis** [comment]
I know, it's hardcoded at the moment. See #11

**Comment by Sangarshanan** [comment]
Got it !

**Comment by martinfleis** [comment]
The main question here is - What should tooltip do by default and what should popup do by default. And whether it should be the same for all map types or based on the data shown on the map.

**Comment by Sangarshanan** [comment]
I think it should ideally be the same as you mentioned in the description of the issue, a sane default and I think the simple map has a good default we can try and replicate in other map types, what do you think ?

**Comment by martinfleis** [comment]
One thing I'd like to make sure is that the actual value of each feature on a choropleth is easily accessible, so it should by default be in a tooltip or a popup. With the default we have in a simple map, it may not happen if the selected column is 11th or higher. That is why I changed it initially but I did not realize it's causing heterogeneity of behaviour.

**Comment by Sangarshanan** [comment]
So if we are setting defaults based on the feature then one issue I see is that we must manually set both the tooltip and popup to None to simply not have them show up on the map

Actually, even now in the simple map, we show the first 10 cols as tooltips by default whereas popups need to be manually specified. How about having everything need to be manually specified to show up? since one can also just create a map and then use the object to add custom HTML tooltips or popup

**Comment by martinfleis** [comment]
> How about having everything to be manually specified to show up?

I think you are right. 

One thing to add then could be a simple `tooltip=True` option, which shows all columns in tootip/popup as a quick way of turning it on. Then we can have `False` which turns it off, `True` which shows all, `list` which specifies columns and `int` which gives you first n column?

**Comment by Sangarshanan** [comment]
Yes !! That would be nice

**Comment by martinfleis** [comment]
> Another thing I wanted to point out was that with Choropleth the column names don't show up on the tooltip just the values, so if we are gonna have multiple tooltips we would need to add column names as well, which will also make them consistent with how popup is shown

Good point. Both tooltip and popup have a range of keywords, in fact, we should somehow expose. https://python-visualization.github.io/folium/modules.html#folium.features.GeoJsonTooltip
