### ISSUE TITLE
DOC: document layer control

### ISSUE THREAD

**Issue by martinfleis** [martinfleis/geopandas-view#12]
`folium.LayerControl()` works only after all layers are in and is removed if a new layer is added to a map, so it is not easy to have it within view. We should optimally figure out a way how to add layer control without the necessity to call `folium.LayerControl()` after `view()` manually.

**Comment by Sangarshanan** [comment]
I did not get the full extent of this, Would there be support for both layer groups and layer control ? I guess that can get a little complicated

**Comment by martinfleis** [comment]
This bit of code generates layer control (you can turn on and off layers).
```py
m = view(world, name='world')
view(cities, name='cities', m=m)
folium.LayerControl().add_to(m)
m
```
![Screenshot 2021-02-14 at 10 24 20](https://user-images.githubusercontent.com/36797143/107874067-ce556580-6eae-11eb-99e2-4b2223bcbbd2.png)

I tried to hook it into `view` but it does not seem to be possible. Layer control needs to be added after all layers are in the map, which we cannot control from within `view`.

Not sure what layer groups are :).

**Comment by Sangarshanan** [comment]
> Not sure what layer groups are :).

Oops though I linked it, I was referring to this plugin https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Plugins.ipynb#FeatureGroupSubGroup

> I tried to hook it into `view` but it does not seem to be possible. Layer control needs to be added after all layers are in the map, which we cannot control from within `view`.

Gotcha, I just noticed there is a map arg you can pass to `view` 😅 so I guess you can call `LayerControl` inside `view` only when you know it's gonna be the final layer that you add, and if someone further adds a new layer then they would need to explicitly set `control=False` or it would just delete the whole LayerControl thing (adding onto your example)
```python
m = view(world, name='world')
view(cities, name='cities', m=m)
folium.LayerControl().add_to(m)
folium.TileLayer('Stamen Terrain',control=False).add_to(m)
m
```
Does this seem like a feature that people should use directly through `folium`? or there could be `layercontrol` arg which would also have its own set of kwargs like `ZIndex`

**Comment by martinfleis** [comment]
> or there could be layercontrol arg which would also have its own set of kwargs like ZIndex

I am not sure if we'll be able to do this in reality.

> Does this seem like a feature that people should use directly through folium?

This may be fine, we just need to make sure to document this (we should maybe start a notebook working as a user guide).
