### ISSUE TITLE
BUG: TypeError: __init__() got an unexpected keyword argument 'map_kwds'

### ISSUE THREAD

**Issue by Sangarshanan** [martinfleis/geopandas-view#14]
Already getting a subset of kwargs for map_kwds in https://github.com/martinfleis/geopandas-view/blob/7c1af1a20c22a01fb178c8eadb6a64451c00d19f/geopandas_view/view.py#L217

So I reckon passing it in __init__() would not be needed 
https://github.com/martinfleis/geopandas-view/blob/7c1af1a20c22a01fb178c8eadb6a64451c00d19f/geopandas_view/view.py#L256

**Comment by martinfleis** [comment]
Ah, true. Forgot to clean it.
