### ISSUE TITLE
ENH: support custom markers

### ISSUE THREAD

**Issue by martinfleis** [martinfleis/geopandas-view#2]
We should support custom markers based on `Circle`, `CircleMarker` or `Marker`. It currently is supported via `folium.GeoJson` but we need to pass folium object to it. This should be wrapped in `view` based on additional keywords.

**Comment by Sangarshanan** [comment]
A Marker can have `location=None, popup=None, tooltip=None, icon=None,
                 draggable=False, **kwargs` as its args where each icon is a `folium.Icon` with its own bunch of args and kwargs.. how do you think we should handle stuff like this? I feel like kwargs inside a kwargs with make things complex. do you think we should expose only limited arguments?

**Comment by martinfleis** [comment]
Hmm, tricky one. I would say let's keep only one level of kwargs (`Marker` level) and document how to work with `folium.Icon` directly. Then if you need something more specific you can do

```py
icon = folium.Icon(<custom kwargs>)
...location=None, popup=None, tooltip=None, icon=icon...
```

**Comment by Sangarshanan** [comment]
Ah yes ! that would be nice

**Comment by Sangarshanan** [comment]
Closed by #22

**Comment by martinfleis** [comment]
@Sangarshanan Not yet, we still need to support this in choropleth.

**Comment by Sangarshanan** [comment]
Oops yes !

**Comment by martinfleis** [comment]
If you have point geometry and want to plot your data? :)

Like this, in case of static plots.

```py
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
cities = gpd.read_file(gpd.datasets.get_path('naturalearth_cities'))
cities = gpd.sjoin(cities, world)
cities.plot("pop_est", scheme='quantiles')
```

<img width="387" alt="Screenshot 2021-02-14 at 16 05 08" src="https://user-images.githubusercontent.com/36797143/107881912-6ae32c00-6ede-11eb-976e-eb3e2ba12e26.png">

**Comment by Sangarshanan** [comment]
Thanks so much for the explanation and the code :) I had not thought about this
