### ISSUE TITLE
Default styling

### ISSUE THREAD

**Issue by martinfleis** [martinfleis/geopandas-view#29]
At the moment, we inherit default styling from `folium.GeoJson`. Opacity, line weight...

It may be worth changing the default because esp. on Choropleths it is not the most beautiful one.

Another thing to consider is highlighting. Now you have to pass something like `highlight_function = lambda x: {"fillColor": "red"}` to turn it on. We may do something by default (i.e. change in opacity).

The same applies to the default behaviour of tooltip and popout. Do we want to show the value of choropleth using Tooltip by default? May be worth doing.

**Comment by Sangarshanan** [comment]
+1 for overriding the default styles for Choropleths. I have been using this as my sane default
```json
style = {
  "color": "black",
  "fillOpacity": 0.5,
  "weight": 1
} 
```
About the tooltip, I normally use the value of the choropleth + an identifier for that row i.e population and city_name, and also this would again make the API inconsistent across plots

**Comment by jorisvandenbossche** [comment]
I think it would be good to use some "opinionated" default. 
(in the end, this is typically for quickly exploring the data, not to produce high-quality figures in which case most have to tweak the figure anyway depending on their use case, as is typically needed with the matplotlib based `plot()`)

For example, with the default `view` with polygons, I find it hard to see the different polygons (the boundaries (edge) are not super visible, especially with the background tile).

I would vote for using by default:

- maybe stronger contrast for the boundary color?
- highlight on hover (I think the default right now is already to use a change in opacity when passing `highlight=True`?)
- tooltip (but then all fields?)
- showing a legend (if applicable, eg when doing a choropleth by passing a `column`)
