### ISSUE TITLE
ENH: custom colours in categorical plots

### ISSUE THREAD

**Issue by martinfleis** [martinfleis/geopandas-view#3]
Categorical plots now loop through all available colours and it is not able to specify which colors and colormaps should be used. We should expose `cmap` to categorical plots.

**Comment by Sangarshanan** [comment]
could wrap around branca-colormap and add args for the same on `view`, which will include #4. Also maybe we can allow directly passing a pre-created colormap, something like this
```python
import branca.colormap as cm
step = cm.StepColormap(
    ["green", "yellow", "red"], vmin=3, vmax=10, index=[3, 4, 8, 10], caption="step"
)
view(world, column="pop_est", cmap=step) # which will automatically set vmin, vmax
```
This will be fillColor in `style_kwds` and there will be others like weight, dashArray, color etc
Borrowed from this example Notebook https://nbviewer.jupyter.org/github/python-visualization/folium/blob/master/examples/Colormaps.ipynb

Have not worked much with colormap before so do lemme know what you think

**Comment by martinfleis** [comment]
I haven't worked with them either so I am happy for whatever solution which works. 

>  Also maybe we can allow directly passing a pre-created colormap

+1 for that.
