### ISSUE TITLE
Stroke color cannot be set in choropleth

### ISSUE THREAD

**Issue by Sangarshanan** [martinfleis/geopandas-view#30]
Since the plots override the color in style_kwargs instead of fillColor, I guess it is not possible to set the stroke/line color for choropleth plots and they just take up the same shade as the filled color, I feel like black could be a good default stroke color that I would like to set to make plots like 
![image](https://user-images.githubusercontent.com/21971847/111871884-6664d400-89b2-11eb-846f-bcccfe49dbbd.png)

**Comment by martinfleis** [comment]
Good catch!

I like to have a default stroke color same as fill color because it makes it easy to create choropleths with LineString and Point geometry. If you set stroke to black, you have to override such a default for line geometry.

**Comment by martinfleis** [comment]
Closed by #31
