### ISSUE TITLE
Use some plugins by default?

### ISSUE THREAD

**Issue by martinfleis** [martinfleis/geopandas-view#41]
I was wondering if we should use some of the plugins by default. Notably, [`Fulscreen`](https://python-visualization.github.io/folium/plugins.html#folium.plugins.Fullscreen) to add a fullscreen button and [`MousePosition`](https://python-visualization.github.io/folium/plugins.html#folium.plugins.MousePosition) showing coordinates of the mouse.

Maybe not, I am not sure about that. We should document using these and some others (`DualMap`, `MiniMap`...) in the notebook anyway.

**Comment by Sangarshanan** [comment]
These will definitely help me ! and there are a bunch of cool plugins but I am not sure about the added complexity of introducing these in the initial version
