### ISSUE TITLE
location kwd not working and zoom_start feature request

### ISSUE THREAD

**Issue by michaelSederlin** [martinfleis/geopandas-view#48]
Hi, 
I did some more playing around today and noticed that passing the location kwd when creating a view doesn't change anything. 
In base would do m = folium.Map(location=(lon,lat), zoom_start=zoom0).
When I change location for gpd-view the map is unchanged. 

```
import geopandas as gpd
from geopandas_view import view
import folium

nybb = gpd.read_file(gpd.datasets.get_path('nybb'))

view(nybb)

view(nybb, location=(50, 44)) # somewhere in Russia
```
Give the same map

I'll also throw in a feature request for the zoom_start kwd. : )

Best, 
Michael

**Comment by martinfleis** [comment]
Ah, yes. We actually pass the keyword but it is then overriden by `fit_bounds` 
https://github.com/martinfleis/geopandas-view/blob/5d4a9a84179b805dc54219cfb02122fabf6b648b/geopandas_view/view.py#L278

We should skip `fit_bounds` if `location` is not None. And we need to expand `_MAP_KWARGS` to include `zoom_start` and other keywords.

You can do it now by specifying the map object outside `view`.

```py
m = folium.Map(location=(40,5), zoom_start=5)
view(nybb, m=m)
```

**Comment by michaelSederlin** [comment]
> 
> You can do it now by specifying the map object outside `view`.
> 
> ```python
> m = folium.Map(location=(40,5), zoom_start=5)
> view(nybb, m=m)
> ```

Ah, that's true. Thanks.
