### ISSUE TITLE
TST: add test suite

### ISSUE THREAD

**Issue by martinfleis** [martinfleis/geopandas-view#6]
Code is currently not tested. We should add tests, although I am not entirely sure how can this be tested apart from "does not fail" :).

**Comment by Sangarshanan** [comment]
could borrow some basic testcases from https://github.com/python-visualization/folium/blob/15f9ceca6c89a718c3819aefd67efa0fc93b896a/tests/test_folium.py#L96 what do you think?

**Comment by martinfleis** [comment]
That looks like a good point to start with. This seems to be a way how to test what is actually drawn https://github.com/python-visualization/folium/blob/15f9ceca6c89a718c3819aefd67efa0fc93b896a/tests/test_folium.py#L226-L229
